version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    docker:
      - image: everettmorgan/circleci-simple-button:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm install && npm run test
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - node_modules
  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install AWS Cli
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install awscli -y
      - run:
          name: Copy to S3
          command: |
            aws s3 sync . s3://simple-button/ --exclude "*" --include "circleci.html" --include "circleci.js"

