version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  build:
    docker:
      - image: everettmorgan/circleci-simple-button:latest
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm install && npm run test
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - node_modules
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circleci
      - run:
          name: Copy to S3
          command: |
            aws s3 sync . s3://simple-button/ --exclude "*" --include "circleci.html" --include "circleci.js"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main